### ISSUE TITLE
Lancers Re-Balance

### ISSUE THREAD

**Issue by Czarified** [TechStack/TS-RTS#209] opened 2020-01-04 06:58 UTC
For whatever reason, lancers seem useless in the current game. Maybe pikemen need a nerf, but lancers seem to even lose vs minions.

**Comment by TechStack** [comment] 2020-01-08 22:59
Lancers were buffed and pikemen Nerf recently not sure if it's enough or if we can close this one yet.
I think Pikeman need an addtional nerf on their weapon at a minimum.

**Comment by TechStack** [comment] 2020-01-11 17:27
Lancers seem able to counter the archers as intended. Closing for now.

**Closed as completed by TechStack** 2020-01-11 17:27 UTC
