### ISSUE TITLE
Resource Gathering by Town Hall seems to be incorrect on MP 

### ISSUE THREAD

**Issue by TechStack** [TechStack/TS-RTS#43] opened 2019-11-16 22:11 UTC
If two players place a town all all players seem to get resources from both town halls

**Comment by Czarified** [comment] 2019-11-16 22:16
Players that do not place the town hall don't see resources ticking up until they place their own down. But, resource values jump to equivalent levels as if they were accumulating the whole time.

**Comment by Czarified** [comment] 2019-11-17 06:30
Duplicate of Economy balance Issue #27 . Closing.

**Closed as completed by Czarified** 2019-11-17 06:30 UTC
Labels: bug, duplicate
